name = "multiobjectiveGraphs"
uuid = "0b54ce73-1c92-4ebd-9a63-95104d042d48"
authors = ["Didier ROBBES <didier.robbes@univ-nantes.fr>"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
